#!/bin/sh -ex

NAME="jessie-backports"
PACKAGES="sphinxsearch"

cat > /etc/apt/sources.list.d/${NAME}.list <<EOF
deb http://http.debian.net/debian $NAME main
EOF

cat > /etc/apt/preferences.d/$NAME <<EOF
Package: *
Pin: release a=$NAME
Pin-Priority: 100

Package: $PACKAGES
Pin: release a=$NAME
Pin-Priority: 500
EOF

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get --force-yes --assume-yes install $PACKAGES

