#!/bin/bash -e
# regenerate nZEDb mysql password

. /etc/default/inithooks

CONF=/var/www/nzedb/config/config.php

PASSWORD=$(mcookie)
sed -i "/DB_PASSWORD/ s|,.*)|, '$PASSWORD')|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=nzedb --pass="$PASSWORD"

